config/routes.rb
Rails.application.routes.draw do
  resources :accounts do
    member do
      patch :convert
      get :reselect_currency
    end
  end
  resources :payments do
    collection do
      patch :carry
      get :transfer
    end
  end
  resources :users, only: :create do
    collection do
      post :confirm
      post :login
    end
  end
  resources :branches, only: %i[index show]
  get '/400', to: 'application#render_400'
  get '*unmatched_route', to: 'application#render_not_found'
  post '*unmatched_route', to: 'application#render_not_found'
  patch '*unmatched_route', to: 'application#render_not_found'
  delete '*unmatched_route', to: 'application#render_not_found'
end

app/models/payment.rb
# payment model
class Payment < ApplicationRecord
  validates_presence_of :from
  validates_presence_of :to
  validates_presence_of :amount
  validates_presence_of :currency
  validates_inclusion_of :currency, in: %w[EUR USD]
  include RecordWithMoney
end

app/controllers/payments_controller.rb
# payments controller
class PaymentsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    respond_with(@payments = Payment.all)
  end

  def show
    with_id_protected { respond_with @payment }
  end

  def create
    @payment = Payment.new(payment_params)
    if CreatePaymentPolicy.new(@payment).allowed? && @payment.save!
      redirect_to @payment
    else
      respond_bad_attributes { render :new }
    end
  end

  def update
    with_id_protected do
      if @payment.update_attributes(payment_params)
        redirect_to @payment
      else
        respond_bad_attributes { render :edit }
      end
    end
  end

  def destroy
    with_id_protected do
      @payment.destroy
      redirect_to payments_path
    end
  end

  def edit
    with_id_protected {}
  end

  # bank_service - docker image name or might be docker machine ip
  def transfer
    @payment = Payment.new
    # resp = RestClient.get 'bank_service:8000/accounts', accept: :json
    @accounts = AccountsForPayment.new(accounts: Account.all).ids
    @others = if defined?(resp) && resp
                JSON.parse(resp.body).map { |entry| entry['id'] }
              else
                []
              end
  end

  def carry
    result = CarryMoney.call(payment_params)
    if result.code == 200
      redirect_to payments_path
    else
      head result.code
    end
  end

  def new
    @payment = Payment.new
  end

  private

  def with_id_protected
    @payment = Payment.find_by_id(params[:id])
    @payment ? yield : render_code(404)
  end

  def payment_params
    params.fetch(:payment, {}).permit(:from, :to, :amount, :currency)
  end
end

app/views/payments/_payment.html.erb
<tr>
  <th><%= payment.from %></th>
  <th><%= payment.to %></th>
  <th><%= payment.amount %></th>
  <th><%= payment.currency %></th>
  <th>
    <%= link_to 'Show', payment %>
    <%= link_to 'Edit', edit_payment_path(payment) %> 
    <%= link_to 'Destroy', payment_path(payment), method: :delete, data: { confirm: 'Are you sure?' } %>
  </th>
</tr>

app/views/payments/edit.html.erb
<h1>Editing payment</h1>

<%= form_for :payment, url: payment_path(@payment), method: :patch do |f| %>
  <% if @payment.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@payment.errors.count, "error") %> prohibited
        this account from being saved:
      </h2>
      <ul>
        <% @payment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :From %><br>
    <%= f.text_field :from %>
  </p>

  <p>
    <%= f.label :To %><br>
    <%= f.text_field :to %>
  </p>

  <p>
    <%= f.label :Amount %> <br>
    <%= f.text_field :amount %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to "Go back", { action: "index" } %>

app/views/payments/index.html.erb
<h1>Payments</h1>

<table>
  <tr>
    <th>From</th>
    <th>To</th>
    <th>Amount</th>
    <th>Currency</th>
    <th>Options</th>
  </tr>
<%= render @payments %>
</table>
<br/>
<%= link_to 'New payment', new_payment_path %> <br/>
<%= link_to 'Transfer to other bank', transfer_payments_path %>

app/views/payments/new.html.erb
<%= form_for :payment, url: payments_path do |f| %>
  <% if @payment.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@payment.errors.count, "error") %> prohibited
        this account from being created:
      </h2>
      <ul>
        <% @payment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :From %><br>
    <%= f.text_field :from %>
  </p>

  <p>
    <%= f.label :To %><br>
    <%= f.text_field :to %>
  </p>

  <p>
    <%= f.label :Amount %><br>
    <%= f.text_field :amount %>
  </p>

  <p>
    <%= f.label :Currency %><br>
    <%= f.select :currency, options_for_select(['USD', 'EUR']) %><br>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to "Go back", { action: "index" } %>

app/views/payments/show.html.erb
<p>From: <%= @payment.from %></p>
<p>To: <%= @payment.to %></p>
<p>Amount: <%= @payment.amount %></p>
<p>Currency: <%= @payment.currency %></p>

<%= link_to 'Go back', { action: "index" } %>

app/views/payments/transfer.html.erb
<h1>Editing payment</h1>

<%= form_for :payment, url: carry_payments_path, method: :patch do |f| %>
  <% if @payment.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@payment.errors.count, "error") %> prohibited
        this account from being saved:
      </h2>
      <ul>
        <% @payment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :From %><br>
    <%= f.select :from, options_for_select(@accounts) %><br>
  </p>

  <p>
    <%= f.label :To %><br>
    <%= f.select :to, options_for_select(@others) %><br>
  </p>

  <p>
    <%= f.label :Amount %> <br>
    <%= f.text_field :amount %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to "Go back", { action: "index" } %>