config/routes.rb
Rails.application.routes.draw do
  resources :accounts do
    member do
      patch :convert
      get :reselect_currency
    end
  end
  resources :payments do
    collection do
      patch :carry
      get :transfer
    end
  end
  resources :users, only: :create do
    collection do
      post :confirm
      post :login
    end
  end
  resources :branches, only: %i[index show]
  get '/400', to: 'application#render_400'
  get '*unmatched_route', to: 'application#render_not_found'
  post '*unmatched_route', to: 'application#render_not_found'
  patch '*unmatched_route', to: 'application#render_not_found'
  delete '*unmatched_route', to: 'application#render_not_found'
end

app/models/account.rb
# describes account model
class Account < ApplicationRecord
  validates_presence_of :currency
  validates_presence_of :name
  validates_presence_of :surname
  validates_presence_of :amount
  validates_inclusion_of :currency, in: %w[EUR USD]
  after_initialize :init
  include RecordWithMoney
  def init
    self.currency ||= 'EUR'
  end
end

app/controllers/accounts_controller.rb
# accounts controller
class AccountsController < ApplicationController
  require 'rest-client'
  require 'currency'
  include AccountsHelper
  skip_before_action :verify_authenticity_token
  # before_action :authenticate_user, only: %i[index show]
  # before_action :authenticate_admin, except: %i[index show]

  def index
    respond_with(@accounts = Account.all)
  end

  def show
    with_id_protected { respond_with @account }
  end

  def create
    @account = Account.new(account_params)
    if @account.save
      redirect_to @account
    else
      respond_bad_attributes { render :new }
    end
  end

  def update
    with_id_protected { change_attributes(account_params) { render :edit } }
  end

  def destroy
    with_id_protected do
      @account.destroy
      redirect_to accounts_path
    end
  end

  def edit
    protect_id
  end

  def new
    @account = Account.new
  end

  def reselect_currency
    protect_id
  end

  def convert
    with_id_protected do
      currency = account_params.require(:currency)
      begin
        change_attributes(money: Money.new(new_amount(currency), currency)) do
          render :reselect_currency
        end
      rescue
        render_code 503
      end
    end
  end

  private

  def change_attributes(attributes)
    if @account.update_attributes attributes
      redirect_to @account
    else
      respond_bad_attributes { yield }
    end
  end

  def new_amount(currency)
    @account.amount * Currency.ratio(@account.currency, currency)
  end

  def account_params
    params.fetch(:account, {}).permit(:name, :surname, :amount, :currency)
  end

  def protect_id
    @account = Account.find_by_id(params[:id])
    render_code 404 unless @account
  end

  def with_id_protected
    @account = Account.find_by_id(params[:id])
    @account ? yield : render_code(404)
  end
end

app/views/accounts/_account.html.erb
<tr>
  <th><%= account.id %></th>
  <th><%= account.name %></th>
  <th><%= account.surname %></th>
  <th><%= account.amount %></th>
  <th><%= account.currency %></th>
  <th>
    <%= link_to 'Show', account %>
    <%= link_to 'Edit', edit_account_path(account) %> 
    <%= link_to 'Destroy', account_path(account), method: :delete, data: { confirm: 'Are you sure?' } %>
    <%= link_to 'Change currency', reselect_currency_account_path(account) %>
</tr>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= form_for :account, url: account_path(@account), method: :patch do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@account.errors.count, "error") %> prohibited
        this account from being saved:
      </h2>
      <ul>
        <% @account.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :Name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :Surname %><br>
    <%= f.text_field :surname %>
  </p>

  <p>
    <%= f.label :Amount %> <br>
    <%= f.text_field :amount %>
  </p>

  <p>
    <%= f.label :Currency %><br>
    <%= f.select :currency, options_for_select(['USD', 'EUR']) %><br>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to "Go back", { action: "index" } %>

app/views/accounts/index.html.erb
<h1>Accounts</h1>

<table>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Surname</th>
    <th>Amount</th>
    <th>Currency</th>
    <th>Options</th>
  </tr>
<%= render @accounts %>
</table>
<br/>
<%= link_to 'New account', new_account_path %>

app/views/accounts/new.html.erb
<%= form_for :account, url: accounts_path do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@account.errors.count, "error") %> prohibited
        this account from being created:
      </h2>
      <ul>
        <% @account.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :Name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :Surname %><br>
    <%= f.text_field :surname %>
  </p>

  <p>
    <%= f.label :Amount %><br>
    <%= f.text_field :amount %>
  </p>

  <p>
    <%= f.label :Currency %><br>
    <%= f.select :currency, options_for_select(['USD', 'EUR']) %><br>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to "Go back", { action: "index" } %>

app/views/accounts/reselect_currency.html.erb
<h1>Convert currency</h1>
<%= ModelInfoDecorator.new(@account).info %>
<p>---------------------------------</p>
<%= view_object(:exchange_info, @account.money).html %>
<p>---------------------------------</p>
<%= form_for :account, url: convert_account_path(@account), method: :patch do |f| %>
  <p>
    <%= f.label :currency %>
    <%= f.select :currency, options_for_select(['USD', 'EUR']) %><br>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to "Go back", { action: "index" } %>

app/views/accounts/show.html.erb
<p>Name: <%= @account.name %></p>
<p>Surname: <%= @account.surname %></p>
<p>Amount: <%= @account.amount %></p>
<p>Currency: <%= @account.currency %></p>

<%= link_to "Go back", { action: "index" } %>